stages:
  - unit test
  - integration test

unit_tests:
  stage: test
  image: node:20
  cache:
    key: ${CI_COMMIT_REF_SLUG} # We create a cache for each branch
    paths:
      - node_modules/
  before_script:
    - npm ci
  script:
    - npm test