stages:
  - build
  - unit tests
  - integration tests
 
typecheck_and_build: # may switch to swc or esbuild if build times become an issue
  stage: build
  image: node:20.11.1-bullseye-slim
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - npm ci
  script:
    - npm run typecheck
    - npm run build

unit_tests:
  stage: unit tests
  image: node:20.11.1-bullseye-slim
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - npm ci
  script:
    - npm test

integration_tests:
  stage: integration tests
  image: node:20.11.1-bullseye-slim
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - npm ci
  script:
    - npm run test:integration
