# Scheduling settings used for this distribution
# algorithm: lpt
# risk_factor: 1
name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  publish_snapshot:
    name: Publish snapshot
    needs:
      - build
      - test-job-1
      - test-job-2
    if: github.event_name == 'push' && github.repository == 'google/truth'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up JDK 11
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: 11
          distribution: temurin
          cache: maven
          server-id: central
          server-username: CI_DEPLOY_USERNAME
          server-password: CI_DEPLOY_PASSWORD
      - name: Publish
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        run: mvn -B clean deploy -DskipTests=true
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66
        with:
          access_token: ${{ github.token }}
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up JDK 11
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: "11"
          distribution: temurin
          cache: maven
      - name: Install
        shell: bash
        run: mvn -B -P!standard-with-extra-repos install -U -DskipTests=true
      - name: Test
        shell: bash
        run: mvn -B -P!standard-with-extra-repos verify -U -Dmaven.javadoc.skip=true
          -DskipTests
      - name: Javadoc Test Run
        shell: bash
        run: mvn -B -P!standard-with-extra-repos javadoc:aggregate -U -DskipTests
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: target/
  test-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66
        with:
          access_token: ${{ github.token }}
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up JDK 11
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: "11"
          distribution: temurin
          cache: maven
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - &a1
        name: Detect available cores
        id: cores
        run: |-
          TOTAL=$(nproc)
          LOAD=$(awk '{print int($1+0.5)}' /proc/loadavg)
          IDLE=$(( TOTAL - LOAD > 1 ? TOTAL - LOAD : 1 ))
          echo "count=$IDLE" >> $GITHUB_OUTPUT
      - name: Run tests
        run: mvn test -Dtest=com.google.common.truth.GraphMatchingTest
          -DfailIfNoSpecifiedTests=false -Dsurefire.forkCount=${{
          steps.cores.outputs.count }} -Dsurefire.reuseForks=true
    needs:
      - build
  test-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66
        with:
          access_token: ${{ github.token }}
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up JDK 11
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: "11"
          distribution: temurin
          cache: maven
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - *a1
      - name: Run tests
        run: mvn test
          -Dtest=com.google.common.truth.GraphMatchingTest,com.google.common.truth.ActualValueInferenceTest,com.google.common.truth.extensions.re2j.Re2jSubjectsTest,com.google.common.truth.ComparisonFailureWithFactsTest,com.google.common.truth.DoubleSubjectTest,com.google.common.truth.ExpectTest,com.google.common.truth.IntStreamSubjectTest,com.google.common.truth.MultimapSubjectTest,com.google.common.truth.PrimitiveFloatArraySubjectTest,com.google.common.truth.ComparableSubjectTest,com.google.common.truth.CorrespondenceTest,com.google.common.truth.ExpectFailureNonRuleTest,com.google.common.truth.ExpectWithStackTest,com.google.common.truth.FloatSubjectTest,com.google.common.truth.IntegerSubjectTest,com.google.common.truth.IterableSubjectCorrespondenceTest,com.google.common.truth.IterableSubjectTest,com.google.common.truth.LongStreamSubjectTest,com.google.common.truth.LongSubjectTest,com.google.common.truth.MapSubjectTest,com.google.common.truth.NumericComparisonTest,com.google.common.truth.ObjectArraySubjectTest,com.google.common.truth.PrimitiveDoubleArraySubjectTest,com.google.common.truth.PrimitiveShortArraySubjectTest,com.google.common.truth.StackTraceCleanerTest,com.google.common.truth.StringSubjectTest,com.google.common.truth.SubjectTest,com.google.common.truth.TableSubjectTest,com.google.common.truth.ThrowableSubjectTest,com.google.common.truth.TruthAssertThatTest,com.google.common.truth.BigDecimalSubjectTest,com.google.common.truth.BooleanSubjectTest,com.google.common.truth.ChainingTest,com.google.common.truth.ClassSubjectTest,com.google.common.truth.CorrespondenceExceptionStoreTest,com.google.common.truth.CustomFailureMessageTest,com.google.common.truth.ExpectFailure8Test,com.google.common.truth.ExpectFailureRuleTest,com.google.common.truth.ExpectFailureTest,com.google.common.truth.ExpectFailureWithStackTraceTest,com.google.common.truth.extension.EmployeeSubjectTest,com.google.common.truth.extension.FakeHrDatabaseTest,com.google.common.truth.FactTest,com.google.common.truth.GuavaOptionalSubjectTest,com.google.common.truth.MathUtilTest,com.google.common.truth.MultisetSubjectTest,com.google.common.truth.OptionalDoubleSubjectTest,com.google.common.truth.OptionalIntSubjectTest,com.google.common.truth.OptionalLongSubjectTest,com.google.common.truth.OptionalSubjectTest,com.google.common.truth.PathSubjectTest,com.google.common.truth.PrimitiveBooleanArraySubjectTest,com.google.common.truth.PrimitiveByteArraySubjectTest,com.google.common.truth.PrimitiveCharArraySubjectTest,com.google.common.truth.PrimitiveIntArraySubjectTest,com.google.common.truth.PrimitiveLongArraySubjectTest,com.google.common.truth.StandardSubjectBuilderTest,com.google.common.truth.StreamSubjectTest,com.google.common.truth.SubjectUtilsTest,com.google.common.truth.TruthFailureSubjectTest,com.google.common.truth.StackTraceCleanerJUnit3Test
          -DfailIfNoSpecifiedTests=false -Dsurefire.forkCount=${{
          steps.cores.outputs.count }} -Dsurefire.reuseForks=true
    needs:
      - build
